extends SceneTree

## Compiles all dialogue + walkie content into a single ordered Markdown
## brief at story/dialogue_brief.md, in player-progression order.
##
## Round-trippable: each chunk is preceded by HTML comments naming its
## source file, type, and identifier. Edit the .md externally, paste
## changes back, and an assistant can map them to the source files.
##
## Run: godot --headless --script res://tools/compile_dialogue_brief.gd --quit

const OUTPUT := "res://story/dialogue_brief.md"

# Player-progression order. Each section is [title, items[]]. Each item is
# a typed array — type-dependent payload follows.
const PROGRESSION: Array = [
	["Hub — Pre-Level-1", [
		["dialogue_stage", "res://dialogue/dial_tone.dialogue", "stage_intro"],
		["dialogue_stage", "res://dialogue/dial_tone.dialogue", "stage_nudge"],
		["dialogue_file", "res://dialogue/companion.dialogue"],
	]],
	["Level 1 — In-Level", [
		["voice_nodes", "res://level/level_1.tscn"],
		["dialogue_file", "res://dialogue/level_1_glitch.dialogue"],
		["dialogue_file", "res://dialogue/level_1_glitch_2.dialogue"],
		["dialogue_file", "res://dialogue/level_1_glitch_3.dialogue"],
		["dialogue_file", "res://dialogue/level_1_nyx.dialogue"],
	]],
	["Hub — Post-Level-1", [
		["dialogue_stage", "res://dialogue/dial_tone.dialogue", "stage_post_1"],
		["dialogue_stage", "res://dialogue/hub_nyx.dialogue", "stage_post_1"],
	]],
	["Level 2 — In-Level", [
		["voice_nodes", "res://level/level_2.tscn"],
		["dialogue_file", "res://dialogue/level_2_glitch.dialogue"],
		["dialogue_file", "res://dialogue/level_2_nyx.dialogue"],
		["dialogue_file_optional", "res://dialogue/glitch_2.dialogue"],
	]],
	["Hub — Post-Level-2", [
		["dialogue_stage", "res://dialogue/dial_tone.dialogue", "stage_post_2"],
		["dialogue_stage", "res://dialogue/hub_nyx.dialogue", "stage_post_2"],
	]],
	["Level 3 — In-Level", [
		["voice_nodes", "res://level/level_3.tscn"],
		["dialogue_file_optional", "res://dialogue/level_3_glitch.dialogue"],
		["dialogue_file", "res://dialogue/level_3_splice_offer.dialogue"],
	]],
	["Hub — Post-Level-3", [
		["dialogue_stage", "res://dialogue/dial_tone.dialogue", "stage_post_3"],
		["dialogue_stage", "res://dialogue/hub_nyx.dialogue", "stage_post_3"],
	]],
	["Level 4 — In-Level", [
		["voice_nodes", "res://level/level_4.tscn"],
		["dialogue_file", "res://dialogue/level_4_glitch.dialogue"],
		["dialogue_file", "res://dialogue/level_4_dialtone.dialogue"],
		["dialogue_file", "res://dialogue/level_4_nyx.dialogue"],
		["dialogue_file", "res://dialogue/level_4_splice_showdown.dialogue"],
	]],
	["Hub — Post-Level-4", [
		["dialogue_stage", "res://dialogue/dial_tone.dialogue", "stage_post_4"],
		["dialogue_stage", "res://dialogue/hub_nyx.dialogue", "stage_post_4"],
		["dialogue_file_optional", "res://dialogue/hub_post4_nyx.dialogue"],
		["dialogue_file_optional", "res://dialogue/hub_post4_splice.dialogue"],
		["dialogue_file_optional", "res://dialogue/hub_post4_glitch.dialogue"],
	]],
]


func _init() -> void:
	var out := _header()
	for section in PROGRESSION:
		out += "\n\n# %s\n" % section[0]
		for item in section[1]:
			out += _render_item(item)
	var f := FileAccess.open(OUTPUT, FileAccess.WRITE)
	if f == null:
		printerr("[compile_dialogue_brief] cannot write ", OUTPUT)
		quit(1)
		return
	f.store_string(out)
	f.close()
	print("[compile_dialogue_brief] wrote %s (%d bytes)" % [OUTPUT, out.length()])
	quit(0)


func _header() -> String:
	return """# Hack The Planet — Dialogue Brief

Auto-generated by `tools/compile_dialogue_brief.gd`. Sections appear in player-progression order.

To regenerate: `godot --headless --script res://tools/compile_dialogue_brief.gd --quit`

To edit and round-trip: copy this file, edit the prose inside the dialogue code blocks (or the `> "..."` walkie quotes), paste the diff back to your assistant. The HTML comment block above each chunk identifies which source file the change maps to.

Walkie triggers fire when the player overlaps each one's Area3D. They appear here in **scene-file order**, which is not necessarily player-progression order — sort them spatially in your head when reading.
"""


func _render_item(item: Array) -> String:
	match item[0]:
		"voice_nodes": return _render_voice_nodes(item[1])
		"dialogue_file": return _render_dialogue_file(item[1], false)
		"dialogue_file_optional": return _render_dialogue_file(item[1], true)
		"dialogue_stage": return _render_dialogue_stage(item[1], item[2])
	return ""


# --- In-level voice nodes (walkies + respawn voice hints) ---------------

func _render_voice_nodes(scene_path: String) -> String:
	if not FileAccess.file_exists(scene_path):
		return "\n*(missing scene: %s)*\n" % _rel(scene_path)
	var text := FileAccess.get_file_as_string(scene_path)
	var walkie_id := _find_walkie_ext_id(text)
	var walkies := _extract_walkies(text, walkie_id) if walkie_id != "" else []
	var respawn_zones := _extract_respawn_zones(text)
	var out := ""
	if walkies.is_empty() and respawn_zones.is_empty():
		out += "\n## In-Level Voice Nodes (`%s`)\n\n*(no walkies or respawn voice hints in this scene)*\n" % _rel(scene_path)
		return out
	if not walkies.is_empty():
		out += "\n## Walkie Triggers (`%s`) — %d total\n" % [_rel(scene_path), walkies.size()]
		for w in walkies:
			out += _format_walkie_chunk(w, scene_path)
	if not respawn_zones.is_empty():
		out += "\n## Respawn Voice Hints (`%s`) — %d total\n" % [_rel(scene_path), respawn_zones.size()]
		for r in respawn_zones:
			out += _format_respawn_chunk(r, scene_path)
	return out


func _find_walkie_ext_id(scene_text: String) -> String:
	var re := RegEx.create_from_string('\\[ext_resource[^\\]]*walkie_trigger\\.tscn[^\\]]*id="([^"]+)"')
	var m := re.search(scene_text)
	if m == null:
		return ""
	return m.get_string(1)


func _extract_walkies(scene_text: String, walkie_id: String) -> Array:
	var nodes: Array = []
	# Split on `[node ` boundaries; each chunk is one node block.
	var chunks := scene_text.split("[node ")
	for chunk in chunks:
		if not chunk.contains('instance=ExtResource("' + walkie_id + '")'):
			continue
		var name_re := RegEx.create_from_string('^name="([^"]+)"')
		var nm := name_re.search(chunk)
		if nm == null:
			continue
		var name := nm.get_string(1)
		var character := _grep_kv(chunk, "character", "&\"DialTone\"")
		character = character.trim_prefix("&\"").trim_suffix("\"")
		if character == "":
			character = "DialTone"
		var line := _grep_kv(chunk, "line", "")
		if line.begins_with("\"") and line.ends_with("\""):
			line = line.substr(1, line.length() - 2)
		var transform := _grep_kv(chunk, "transform", "")
		var pos := _extract_position(transform)
		var require_flag := _grep_kv(chunk, "require_flag", "")
		nodes.append({
			"name": name,
			"character": character,
			"line": line,
			"position": pos,
			"require_flag": require_flag,
		})
	return nodes


func _grep_kv(body: String, key: String, default: String) -> String:
	for raw_line: String in body.split("\n"):
		var stripped: String = raw_line.strip_edges()
		var prefix: String = key + " = "
		if stripped.begins_with(prefix):
			return stripped.substr(prefix.length())
	return default


func _extract_position(transform_str: String) -> String:
	var re := RegEx.create_from_string("Transform3D\\((.+)\\)")
	var m := re.search(transform_str)
	if m == null:
		return "?"
	var parts := m.get_string(1).split(",")
	if parts.size() < 12:
		return "?"
	return "(%s, %s, %s)" % [
		parts[9].strip_edges(),
		parts[10].strip_edges(),
		parts[11].strip_edges(),
	]


func _format_walkie_chunk(w: Dictionary, scene_path: String) -> String:
	var line_text: String = w.line if w.line != "" else "*(no line set)*"
	return """
<!-- source: %s -->
<!-- type: walkie -->
<!-- node: %s -->
<!-- character: %s -->

### `%s` — %s
**Position:** %s

> %s
""" % [
		_rel(scene_path),
		w.name,
		w.character,
		w.name,
		w.character,
		w.position,
		line_text,
	]


# --- Dialogue file / stage rendering ------------------------------------

func _render_dialogue_file(path: String, optional: bool) -> String:
	if not FileAccess.file_exists(path):
		if optional:
			return "\n*(file not yet authored: `%s`)*\n" % _rel(path)
		return "\n*(missing: %s)*\n" % _rel(path)
	var content := FileAccess.get_file_as_string(path)
	return """
<!-- source: %s -->
<!-- type: dialogue_file -->

## `%s`

```
%s
```
""" % [_rel(path), _rel(path), content]


func _render_dialogue_stage(path: String, stage: String) -> String:
	if not FileAccess.file_exists(path):
		return "\n*(missing: %s)*\n" % _rel(path)
	var content := FileAccess.get_file_as_string(path)
	var stage_text := _extract_stage(content, stage)
	if stage_text == "":
		return """
<!-- source: %s -->
<!-- type: dialogue_stage -->
<!-- stage: %s -->

## `%s` → `~ %s`

*(stage not found in file)*
""" % [_rel(path), stage, _rel(path), stage]
	return """
<!-- source: %s -->
<!-- type: dialogue_stage -->
<!-- stage: %s -->

## `%s` → `~ %s`

```
%s
```
""" % [_rel(path), stage, _rel(path), stage, stage_text]


func _extract_stage(content: String, stage: String) -> String:
	# Capture from `~ stage_X` until either:
	#   - next `~ stage_Y` (a different top-level stage), or
	#   - a `# ── ... ──` visual section divider, or
	#   - EOF.
	# Sub-sections (post_1_menu, intro_who etc.) live INSIDE a stage cluster
	# and are kept.
	var lines := content.split("\n")
	var out: Array[String] = []
	var capturing := false
	for line: String in lines:
		if line.begins_with("~ " + stage):
			capturing = true
			out.append(line)
		elif capturing and (line.begins_with("# ──") or _is_other_stage_header(line, stage)):
			break
		elif capturing:
			out.append(line)
	return "\n".join(out).strip_edges()


func _is_other_stage_header(line: String, current_stage: String) -> bool:
	return line.begins_with("~ stage_") and not line.begins_with("~ " + current_stage)


func _rel(path: String) -> String:
	return path.replace("res://", "")


# --- Respawn voice hint extraction --------------------------------------
#
# RespawnMessageZones expose `voice_character = &"X"` + `voice_line = "..."`
# inline on the node block (no walkie-trigger ext_resource indirection).
# Detected purely by property presence on each node chunk.

func _extract_respawn_zones(scene_text: String) -> Array:
	var nodes: Array = []
	var chunks := scene_text.split("[node ")
	for chunk in chunks:
		var name_re := RegEx.create_from_string('^name="([^"]+)"')
		var nm := name_re.search(chunk)
		if nm == null:
			continue
		var vc_raw := _grep_kv(chunk, "voice_character", "")
		if vc_raw == "":
			continue
		var character := vc_raw.trim_prefix("&\"").trim_suffix("\"")
		if character == "":
			continue
		var voice_line := _grep_kv(chunk, "voice_line", "")
		if voice_line.begins_with("\"") and voice_line.ends_with("\""):
			voice_line = voice_line.substr(1, voice_line.length() - 2)
		if voice_line == "":
			continue
		var transform := _grep_kv(chunk, "transform", "")
		var pos := _extract_position(transform)
		nodes.append({
			"name": nm.get_string(1),
			"character": character,
			"line": voice_line,
			"position": pos,
		})
	return nodes


func _format_respawn_chunk(r: Dictionary, scene_path: String) -> String:
	return """
<!-- source: %s -->
<!-- type: respawn_voice_hint -->
<!-- node: %s -->
<!-- character: %s -->

### `%s` — %s (respawn hint)
**Position:** %s

> %s
""" % [
		_rel(scene_path),
		r.name,
		r.character,
		r.name,
		r.character,
		r.position,
		r.line,
	]
